<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
    public function search($title,$addedDateFrom,$addedDateTo,$updatedDateFrom,$updatedDateTo,$launchDateFrom,$launchDateTo,$status){
        $qb = $this->createQueryBuilder('o')
            ->select('o');
        if($title != null){
           $qb->andwhere('o.product LIKE :title')
               ->setParameter('title','%'.$title.'%')
           ;
        }

        if($status != null and $status!= 'default'){
            $qb->andWhere('o.status = :status')
                ->setParameter('status',$status);
        }

        if($addedDateFrom != null or $addedDateTo != null){
            if($addedDateFrom != null){
                $addedDateFrom = \DateTime::createFromFormat('m/d/Y', $addedDateFrom);
            }
            if($addedDateTo != null){
                $addedDateTo = \DateTime::createFromFormat('m/d/Y', $addedDateTo);
            }
            $qb->andWhere(
                $qb->expr()->between(
                    'o.datetime',
                    ':addedFrom',
                    ':addedTo'
                )
            )
                ->setParameter('addedFrom', $addedDateFrom)
                ->setParameter('addedTo', $addedDateTo);
        }

        if($updatedDateFrom != null or $updatedDateFrom != null){
            if($updatedDateFrom != null){
                $updatedDateFrom = \DateTime::createFromFormat('m/d/Y', $updatedDateFrom);
            }
            if($updatedDateTo != null){
                $updatedDateTo = \DateTime::createFromFormat('m/d/Y', $updatedDateTo);
            }
            $qb->andWhere(
                $qb->expr()->between(
                    'o.datetime',
                    ':updatedFrom',
                    ':updatedTo'
                )
            )
                ->setParameter('updatedFrom', $updatedDateFrom)
                ->setParameter('updatedTo', $updatedDateTo);
        }

        if($launchDateTo != null or $launchDateFrom != null){
//            var_dump($launchDateFrom);
//            var_dump($launchDateTo);
            if($launchDateFrom != null){
                $launchDateFrom = \DateTime::createFromFormat('m/d/Y', $launchDateFrom);
            }
            if($launchDateTo != null){
                $launchDateTo = \DateTime::createFromFormat('m/d/Y', $launchDateTo);
            }

//            var_dump($launchDateFrom);
//            var_dump($launchDateTo);

            $qb->andWhere(
                $qb->expr()->between(
                    'o.launchDate',
                    ':launchFrom',
                    ':launchTo'
                )
            )
                ->setParameter('launchFrom', $launchDateFrom)
                ->setParameter('launchTo', $launchDateTo);
        }

//        var_dump($qb->getQuery()->getSQL());
        return $qb->getQuery()->getResult();
    }
}
